###Statistical Data Analysis Problem sheet 3

1. Exercise 1

In [37]:
#importing all the libraries
import pandas as pd
import numpy as np

In [38]:
#getting the X values as a dataframe
dfx = pd.read_csv('/content/drive/MyDrive/1-DS/X.txt', sep=",", header=None)

In [39]:
#getting the Y values as a dataframe
dfy = pd.read_csv('/content/drive/MyDrive/1-DS/Y.txt', header= None)

Now we need to convert them into matrix

In [40]:
#converting to numpy array to get matrix
x = dfx.to_numpy()
y = dfy.to_numpy()

In [41]:
#adding an identity column to the x to equalize the full rank p + 1
x = np.insert(x, 0, 1.0, axis=1)

**As the LS estimator is equivalent to the ML estimator based on the maximization of the log likelihood, we can estimate the beta hat from it.**

In [42]:
#beta hat estimating
xt = np.transpose(x)
xtx = xt.dot(x)

beta = np.linalg.inv(xtx).dot(xt).dot(y)
beta

array([[-0.00800698],
       [ 0.88161162],
       [-2.45938171],
       [-0.97715699]])

* *Here we get B0, B1, B2 and B3 for the multiple linear regression model*

* As the mean is 0 and the constant variance is 1 which gives us that N is a standard normal distrbution.

In [43]:
#now we can get the sigma hat square in the multiple linear regression model
sgms =  (np.transpose(y-x.dot(beta))*(y-x.dot(beta))) / 201
sgms

array([[ 1.43756944e-04, -2.60179376e-04,  4.88288715e-05, ...,
        -8.27929177e-04, -5.93215518e-04, -6.80968604e-04],
       [-2.60179376e-04,  4.70887219e-04, -8.83732288e-05, ...,
         1.49843263e-03,  1.07363470e-03,  1.23245515e-03],
       [ 4.88288715e-05, -8.83732288e-05,  1.65853462e-05, ...,
        -2.81216658e-04, -2.01493183e-04, -2.31299633e-04],
       ...,
       [-8.27929177e-04,  1.49843263e-03, -2.81216658e-04, ...,
         4.76823381e-03,  3.41646407e-03,  3.92185420e-03],
       [-5.93215518e-04,  1.07363470e-03, -2.01493183e-04, ...,
         3.41646407e-03,  2.44791410e-03,  2.81002872e-03],
       [-6.80968604e-04,  1.23245515e-03, -2.31299633e-04, ...,
         3.92185420e-03,  2.81002872e-03,  3.22571018e-03]])

In [44]:
#now we can also get the adjusted estimator of the variance hat
sgad = ((np.transpose(y).dot(y))- (np.transpose(beta).dot(xt).dot(y))) / (201 - 3 - 1)
sgad

array([[0.97422819]])